# Generated by Django 5.0.7 on 2024-08-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationcontent",
            name="prompt",
            field=models.CharField(default=1, max_length=300, verbose_name="Prompt"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="conversation",
            name="conversationId",
            field=models.CharField(
                max_length=2, unique=True, verbose_name="Conversation ID"
            ),
        ),
    ]
