# Generated by Django 5.0.7 on 2024-08-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_conversationcontent_prompt_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hint",
            name="conversationId",
        ),
        migrations.RemoveField(
            model_name="hint",
            name="language",
        ),
        migrations.RemoveField(
            model_name="hint",
            name="scenario",
        ),
        migrations.RemoveField(
            model_name="hint",
            name="targetLanguage",
        ),
        migrations.RemoveField(
            model_name="hint",
            name="targetLanguageId",
        ),
        migrations.AddField(
            model_name="hint",
            name="chinese",
            field=models.CharField(default="", max_length=50, verbose_name="Chinese"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hint",
            name="italian",
            field=models.CharField(default="", max_length=50, verbose_name="Italian"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hint",
            name="spanish",
            field=models.CharField(default="", max_length=50, verbose_name="Spanish"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="conversationcontent",
            name="contentId",
            field=models.CharField(
                max_length=3, unique=True, verbose_name="Content ID"
            ),
        ),
    ]
