# Generated by Django 5.0.7 on 2024-09-22 23:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_remove_hint_conversationid_remove_hint_language_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appusers",
            name="emailAddress",
        ),
        migrations.RemoveField(
            model_name="appusers",
            name="id",
        ),
        migrations.RemoveField(
            model_name="appusers",
            name="joinDate",
        ),
        migrations.RemoveField(
            model_name="appusers",
            name="languageId",
        ),
        migrations.RemoveField(
            model_name="appusers",
            name="level",
        ),
        migrations.RemoveField(
            model_name="appusers",
            name="name",
        ),
        migrations.RemoveField(
            model_name="appusers",
            name="userId",
        ),
        migrations.AddField(
            model_name="appusers",
            name="email",
            field=models.EmailField(
                default=django.utils.timezone.now,
                max_length=254,
                primary_key=True,
                serialize=False,
                verbose_name="User Email",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appusers",
            name="language",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=50,
                verbose_name="Language",
            ),
            preserve_default=False,
        ),
    ]
