# Generated by Django 5.0.7 on 2024-09-22 23:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_remove_appusers_email_remove_appusers_language_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="languageId",
            field=models.CharField(max_length=10, verbose_name="language Id"),
        ),
    ]
