# Generated by Django 5.0.7 on 2024-09-22 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0006_alter_language_languageid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appusers",
            name="id",
        ),
        migrations.RemoveField(
            model_name="appusers",
            name="joinDate",
        ),
        migrations.RemoveField(
            model_name="appusers",
            name="level",
        ),
        migrations.RemoveField(
            model_name="appusers",
            name="name",
        ),
        migrations.RemoveField(
            model_name="appusers",
            name="userId",
        ),
        migrations.AlterField(
            model_name="appusers",
            name="emailAddress",
            field=models.EmailField(
                max_length=254,
                primary_key=True,
                serialize=False,
                verbose_name="User Email",
            ),
        ),
        migrations.AlterField(
            model_name="appusers",
            name="languageId",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="events.language",
            ),
        ),
    ]
