# Generated by Django 5.0.7 on 2024-09-23 00:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0007_remove_appusers_id_remove_appusers_joindate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appusers",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="appusers",
            name="emailAddress",
            field=models.EmailField(
                max_length=30, unique=True, verbose_name="User Email"
            ),
        ),
    ]
