# Generated by Django 5.0.7 on 2024-09-23 01:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0009_alter_appusers_languageid_alter_language_languageid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="languageId",
            field=models.IntegerField(verbose_name="language Id"),
        ),
    ]
