# Generated by Django 5.0.7 on 2024-10-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0010_alter_language_languageid"),
    ]

    operations = [
        migrations.AddField(
            model_name="appusers",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
