# Generated by Django 5.0.7 on 2024-10-09 12:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0011_appusers_birth_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appusers",
            old_name="birth_date",
            new_name="birthDate",
        ),
    ]
