# Generated by Django 5.0.7 on 2024-10-19 13:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0013_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="hint",
            name="arabic",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=50, verbose_name="Italian"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hint",
            name="french",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=50, verbose_name="Chinese"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hint",
            name="german",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=50, verbose_name="Spanish"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hint",
            name="japanese",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=50, verbose_name="Italian"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hint",
            name="russian",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=50, verbose_name="Chinese"
            ),
            preserve_default=False,
        ),
    ]
